### ISSUE TITLE
faces/create encodes response ControlParameters incorrectly

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndnd#80]
In response to `faces/create` comamnd, YaNFD is encoding the ControlParameters structure incorrectly.

## YaNFD command line and relevant output

YaNFD revision e195ffe9228ccbd7aceba01fa5e987f5d03b9e92

```text
ubuntu@ndndev:~/YaNFD$ sudo ./yanfd -config yanfd.sample.yml 

  INFO[0010] [TCPListener, tcp4://127.0.0.1:6363] Accepting new TCP face tcp4://127.0.0.1:42364
  INFO[0010] [FaceMgmt] Created face with URI udp4://127.0.0.1:7001
  INFO[0010] [FaceTable] Unregistered FaceID=7
```

## NDNts snippet and relevant output

https://github.com/yoursunny/NDNts/blob/60c652ba0c686211de2cdcf58ea3b18a3eced9a9/integ/nfdmgmt-interop/face-rib.ts#L16-L29

```text
ubuntu@ndndev:~/NDNts$ NDNTS_UPLINK=tcp://127.0.0.1:6363 corepack pnpm literate integ/nfdmgmt-interop/face-rib.ts

[faces/create]
  ControlParameters faceId=8 uri="udp4://127.0.0.1:7001" localUri="udp4://127.0.0.1:6363" baseCongestionMarkingInterval=100000000 defaultCongestionThreshold=65536 mtu=1300
node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

undefined !== 2

    at file:///home/ubuntu/NDNts/integ/nfdmgmt-interop/face-rib.ts:21:8
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: 2,
  operator: 'strictEqual'
}

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
```

## YaNFD Packet Trace

Offending packet is in frame 11 of [1.pcapng.gz](https://github.com/user-attachments/files/18222865/1.pcapng.gz).

The payload of this packet is:

```text
6550 
  6601c8
  67024f4b
  6847 Controlparameters
    690108 FaceId
    7215756470343a2f2f3132372e302e302e313a37303031 Uri
    8115756470343a2f2f3132372e302e302e313a36333633 LocalUri
    870405f5e100 BaseCongestionMarkingInterval
    880400010000 DefaultCongestionThreshold
    89020514 Mtu
    6c0100 Flags
    850102 FacePersistency
```

This does not match the sub TLV order as specified in [ControlCommand rev53](https://redmine.named-data.net/projects/nfd/wiki/ControlCommand/53):

```abnf
ControlParameters               = CONTROL-PARAMETERS-TYPE TLV-LENGTH
                                    [Name]
                                    [FaceId]
                                    [Uri]
                                    [LocalUri]
                                    [Origin]
                                    [Cost]
                                    [Capacity]
                                    [Count]
                                    [Flags]
                                    [Mask]
                                    [Strategy]
                                    [ExpirationPeriod]
                                    [FacePersistency]
                                    [BaseCongestionMarkingInterval]
                                    [DefaultCongestionThreshold]
                                    [Mtu]
```

According to [NDN-TLV spec](https://github.com/named-data/NDN-packet-spec/blob/815503cfe6bb5309dcd5940de0c3a087a6db3354/tlv.rst):

> A compliant TLV format decoder should follow the order, quantity, and presence requirements of the recognized elements defined in the corresponding specification.

Hence, the ordering among sub TLVs are indeed significant.

## NFD Packet Trace

Running the same scenario with NFD 24.07-1-gee97f534 creates the traffic trace [2.pcapng.gz](https://github.com/user-attachments/files/18222871/2.pcapng.gz).
Equivalent packet is in frame 11.

The payload of this packet is:

```text
6551
  6601c8
  67024f4b
  6848 ControlParameters
    69020108 FaceId
    7215756470343a2f2f3132372e302e302e313a37303031 Uri
    8115756470343a2f2f3132372e302e302e313a36333633 LocalUri
    6c0104 Flags
    850102 FacePersistency
    870405f5e100 BaseCongestionMarkingInterval
    880400010000 DefaultCongestionThreshold
    89020514 Mtu
```

**Comment by zjkmxy** [comment]
This is because the encoding of mgmt protocol in `python-ndn` and `go-ndn` is based on the old version of Spec in 2019.
It seems the spec of the mgmt protocol is changed recently and the maintainers of these packets are not aware of that change.
Will fix the spec ASAP.

Also, if you do not mind to do us a favour, I wish next time when any spec is modified, an issue could be created in `python-ndn` and `go-ndn` GitHub repo ASAP.
Since our inboxes are fulfilled with email exchanges, it is quite often that we miss a breaking change in ndn-cxx or an email from NFD mailing list.
I understand it is our fault for not checking them but we are really overloaded and appreciate reminders.

**Comment by Pesa** [comment]
I'm not aware of any recent management protocol changes. I see a modification by Junxiao in Jan 2024 but the comment points to an unrelated commit so I'm very confused. @yoursunny can you please clarify?

Btw, it's possible that the ndn-cxx implementation always used this order but the spec on the wiki was wrong and was just updated to reflect the implementation.

**Comment by Pesa** [comment]
> According to [NDN-TLV spec](https://github.com/named-data/NDN-packet-spec/blob/815503cfe6bb5309dcd5940de0c3a087a6db3354/tlv.rst):
> 
> > A compliant TLV format decoder should follow the order, quantity, and presence requirements of the recognized elements defined in the corresponding specification.
> 
> Hence, the ordering among sub TLVs are indeed significant.

This deduction is completely wrong btw. You are using the rules of the network-layer protocol (NDN) and applying them to an application layer protocol (NFD mgmt). Just because the latter uses a similar TLV-based encoding does not imply that it must also follow the same protocol rules and constraints.

**Comment by zjkmxy** [comment]
> Btw, it's possible that the ndn-cxx implementation always used this order but the spec on the wiki was wrong and was just updated to reflect the implementation.

I think this is the case. When Eric adds the congestion control parameters to the mgmt protocol, the order in ndn-cxx is different from the order in the wiki:

https://github.com/named-data/ndn-cxx/blob/07d05c97b435a8de5ff76986df6a0cb3a50a6484/src/mgmt/nfd/control-parameters.cpp#L50-L69

https://redmine.named-data.net/projects/nfd/wiki/ControlCommand/40/diff

**Comment by zjkmxy** [comment]
6e238d0 should fix it.

**Comment by pulsejet** [comment]
Please reopen if the issue persists
